name: Q3action
on: 
  workflow_run:
    workflows: ["Q2action"]
    types:
      - completed
permissions:
 contents: write
jobs:
  q3action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Checkout du dépôt
      uses: actions/checkout@v3
    - name: transfert de toto.txt dans archive
      run: |
        echo "Alexandre Pradignac" > Q3_archive_java.txt
        cat Q3.java >> Q3_archive_java.txt
    - name: Commit et push des fichiers
      run: |
        git config user.name A1exPrdgc
        git config user.email pa230262@etu.univ-lehavre.fr
        git add Q3_archive_java.txt
        git commit -m "Ajout Q3_archive_java.txt" || echo "rien"
        git push