name: Q4action
on: 
  workflow_run:
    workflows: ["Q3action"]
    types:
      - completed
permissions:
 contents: write
jobs:
  q4action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Checkout du dépôt
      uses: actions/checkout@v3
    - name: Définir variables d’archive
      id: vars
      run: |
        DATE=$(date +"%d-%m-%Y")
        echo "DATE=$DATE" >> $GITHUB_ENV
        echo "ARCHIVE=Q4_archive_${DATE}.txt" >> $GITHUB_ENV
    - name: transfert de toto.txt dans archive
      run: |
        echo "Alexandre Pradignac" > ${ARCHIVE}
        cat Q4.java >> ${ARCHIVE}
    - name: Commit et push des fichiers
      run: |
        git config user.name A1exPrdgc
        git config user.email pa230262@etu.univ-lehavre.fr
        git add ${ARCHIVE}
        git commit -m "Ajout ${ARCHIVE}" || echo "rien"
        git push

