name: Q6action
on:
  workflow_run:
    workflows: ["Q5action"]
    types:
      - completed
permissions:
  contents: write
jobs:
  q6action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Création d'archive avec date et stats
        run: |
          DATETIME=$(date '+%d-%m-%Y-%H%M%S')
          FILENAME="Q6_archive_${DATETIME}.txt"

          echo "Alexandre Pradignac" > ${FILENAME}
          echo "" >> ${FILENAME}
          echo "Contenu de Q6.java:" >> ${FILENAME}
          cat Q6.java >> ${FILENAME}
          echo "" >> ${FILENAME}
          echo "Statistiques de Q6.java:" >> ${FILENAME}
          echo "Nombre de caractères: $(wc -c < Q6.java)" >> ${FILENAME}
          echo "Nombre de lignes: $(wc -l < Q6.java)" >> ${FILENAME}

      - name: Création de fichier de différences
        run: |
          FILES=$(ls -t Q6_archive_*.txt 2>/dev/null | head -n 2)
          COUNT=$(echo "$FILES" | wc -l)

          if [ "$COUNT" -ge 2 ]; then
            LAST=$(echo "$FILES" | sed -n '1p')
            PREVIOUS=$(echo "$FILES" | sed -n '2p')
            
            echo "Différences entre $PREVIOUS et $LAST:" > Q6_différences.txt
            echo "" >> Q6_différences.txt
            diff "$PREVIOUS" "$LAST" >> Q6_différences.txt || true
          else
            echo "Pas asez de fichier" > Q6_différences.txt
          fi

      - name: Commit et push archives
        run: |
          git config --local user.email "pa230262@univ-lehavre.fr"
          git config --local user.name "A1exPrdgc"
          git add Q6_archive_*.txt Q6_différences.txt
          git diff --staged --quiet || git commit -m "Q6: Archive Q6.java avec date, stats et différences"
          git pull --rebase origin ${{ github.ref_name }}
          git push